### ISSUE TITLE
EyePACS AIROGS pre-processing

### ISSUE THREAD

**Issue by abhirooptalasila** [TheBeastCoding/glaucoma-dataset-metadata#32]
Hi
Can you give more details/code on how the images in AIROGS were pre-processed to make the light-V2 version?

**Comment by TheBeastCoding** [comment]
There is no major changes in the preprocessing compared to v1. I simply downscaled images to 512x512 pixels instead of 256x256 pixels after the pixel selection process.

**Comment by abhirooptalasila** [comment]
Where can I find the preprocessing code for v1?

**Comment by TheBeastCoding** [comment]
There is no code available, but there is a paper on the process here:
https://ieeexplore.ieee.org/abstract/document/10270429

Additionally, I have updated the about section in the EyePACS-light-v2 for you to provide a high level overview of the preprocessing steps.
